config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'
  get 'questions/new'
  get 'questions/edit/:id' =>'questions#edit'
  patch 'questions/edit/:id' => 'questions#update'
  get 'questions/answer'
  post 'questions/result' => 'questions#result'
  get 'questions/result' => 'posts#index'
  get 'questions/create' => 'questions#create'
  post 'questions/create' => 'questions#create'
  get 'questions/delete/:id' => 'questions#delete'
  post 'questions/answer_check' => 'questions#answer_check'
  get 'users/new'
  get 'users/create'
  get 'users/show/:id' => 'users#show'
  get 'users/edit/:id' =>'users#edit'
  patch 'users/edit/:id' => 'users#update'
  get 'users/delete/:id' => 'users#delete'
  post 'users/create' =>'users#create'
  post 'users/login' => 'users#login'
  get '' => 'home#index'
  get 'new' => 'home#new' 
  get 'posts' => 'posts#index'
  post 'posts' => 'posts#create'
  get 'posts/new'
  get 'posts/show'
  get 'posts/delete/:id' => 'posts#delete'
  get 'posts/edit/:id' => 'posts#edit'
  patch 'posts/edit/:id' => 'posts#edit'
  post 'login' => 'sessions#create'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :contacts,only: [:new,:create]
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/back' => 'contacts#back'
  get 'posts/questions/new' => 'post_questions#new'
  post 'posts/questions/new' =>'post_questions#create'
  get 'posts/questions/list' =>'post_questions#list'
  get 'posts/questions/start/:id' => 'post_questions#start'
  get 'posts/questions/answer/:id' => 'post_questions#answer'
  post 'posts/questions/answer/:id' => 'post_questions#result'
  get 'posts/questions/edit/:id' => 'post_questions#edit'
  patch 'posts/questions/edit/:id' => 'post_questions#update'
  get 'posts/questions/delete/:id' => 'post_questions#delete'
  get 'mylist/create/:id' => 'mylist#create'
  get 'mylist/destroy/:id' => 'mylist#destroy'
  get 'mylist/delete/:id' => 'mylist#delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    validates :subject ,presence: true
    validates :problem ,presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :require_admin, only:[:create]

  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @questions = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update question_params
      redirect_to '/questions/index', notice:'更新しました'
    else
      render 'edit'
    end
  end

  def delete
    @question =Question.find(params[:id])
    @question.destroy
    redirect_to '/questions/index' ,notice: '問題を削除しました'
  end

  def answer
    @user = current_user
    unless @user.admin
      if @user.point < 100
        redirect_to '/questions/new', notice: 'ポイントが足りません'
      elsif @user.point >= 100
        used_point = @user.point - 100
        @user.update(point: used_point)
      end
    end

      answers = []
      @answers = []
      @id = []
      num = 0

      # データベースからランダムにデータをとりだす
      @questions = Question.order("RANDOM()").limit(10)                   
      # 取り出したデータのanswerカラムのデータを一つずつanswers配列に格納,misatakeカラムのデータをdummys配列に格納
      @questions.each do |question|
          answers << question.answer
          answers << question.mistake1
          answers << question.mistake2
          answers << question.mistake3
          @id << question.id 
      end 

      #answersに格納したデータを１つの問題ごとに分割し、選択肢作成
      answers = answers.each_slice(4).to_a

      #選択肢をシャッフル
      while num<10 do
        @answers[num] = answers[num].shuffle
        num +=1
      end
  end


  def result
    user = current_user
    point = user.point
    result = []
    @questions = []
    @answers = []
    (0..9).each do |question_num|
      question = Question.find(params["question#{question_num}"])
      @questions << question.problem
      @answers << question.answer
      if  params["selfanswer#{question_num}"] == question.answer
        result[question_num] = "正解"
      else
        result[question_num] = "不正解"
      end
    end

    @number_questions = @questions.size
    @correct = result.count("正解")
    answer_rate = @correct.to_f / @number_questions.to_f

    if answer_rate < 0.2
      @msg = '頑張ろう'
      user.update(point:point + 10)
      @point = 10
    elsif answer_rate >=0.2 && answer_rate < 0.4
      @msg = 'うんうん'
      user.update(point:point + 20)
      @point = 20
    elsif answer_rate >= 0.4 && answer_rate < 0.6
      @msg = 'あと半分！'
      user.update(point:point + 50)
      @point = 50
    elsif answer_rate >= 0.6 && answer_rate <0.8
      @msg = 'もうちょっと！'
      user.update(point:point + 70)
      @point = 70
    elsif answer_rate >=0.8 && answer_rate < 1
      @msg = 'あと一歩'
      user.update(point:point + 150)
      @point = 150
    elsif answer_rate == 1
      @msg = '満点おめでとう！！'
      user.update(point:point + 200 )
      @point = 200
    end
  end

  def create 
    @question = Question.new question_params
    if @question.save
      redirect_to '/questions/index', notice:'保存しました'
    else
      @questions = Question.all
      render 'index'
    end
  end

  private
  def question_params
    params.require(:question).permit(:subject,:problem,:answer,:mistake1,:mistake2,:mistake3)
  end

  def session_params
    params.require(:session).permit(:answer)
  end

  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/answer.html.erb
<div class="answer_wrap container col-md-7">
    <h1>問題</h1>
    <div class="timer_area">
        <div class="timer"><i class="far fa-clock"></i>残り時間<span id="min">10</span>分<span id = second>0</span>秒</div>
    </div>
    <h2>問題を読んで正しいもの一つ選んで解答してね<br>英文は文を読んだ後に問題分に相応しい回答を選択してね</h2>
    <p>一つの問題で２つ以上のチェックを入れると不正解になるから気をつけよう！</p>
    <%= javascript_pack_tag 'countdownTimer' %>
    <div class="question2_wrap">
        <% question_num=0 %>
        <% number = 1 %>
        <%= form_with url: questions_result_path do |f|  %>
            <% @questions.each do |obj| %>
                <% choices=0 %>
                <div class="question">
                    <p class="number">第<%= number %>問:&nbsp;<%= obj.problem %></p>
                    <%= hidden_field_tag "question#{question_num}", @id[question_num] %>
                    <% 4.times do %>
                    <div class="choices">
                        <p>
                            <%= check_box_tag "selfanswer#{question_num}",@answers[question_num][choices],false,{class:'check'} %>
                            <%= label_tag @answers[question_num][choices]%>
                        </p>
                    </div>
                    <% choices+=1 %>
                    <% end %>
                </div>
                <% question_num+=1 %>
                <% number +=1%>
            <% end %>
        <div class="end-btn">
            <%= submit_tag '解答終了',{class:'btn-sticky',id:'end'} %>
        </div>
        <% end %>
    </div>
</div>

app/views/questions/edit.html.erb
<div class="question-edit-wrap">
    <div class="question-edit container">
        <h1>問題編集</h1>
        <%= form_for(@question,url:{controller: 'questions',action: 'update'}) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
            <label for="subject">教科</label>
            <%= f.select :subject,{'国語':1,'数学':2,'英語':3}, {include_blank:'選択してださい'},{class: 'form-control'} %>
        </div>
        <div class="form-group">
            <label for="problem">問題文</label>
            <%= f.text_area :problem,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :answer,'答え' %>
            <%= f.text_field :answer,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake1,'不正解１' %>
            <%= f.text_field :mistake1,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake2,'不正解2' %>
            <%= f.text_field :mistake2,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake3,'不正解3' %>
            <%= f.text_field :mistake3,{class:'form-control'} %>
        </div>
        <div class="question-edit-btn">
            <%= f.submit '更新する',{class:'btn-sticky'} %>
        </div>
        <% end %>
    </div>
</div>

app/views/questions/index.html.erb
<div class="question-index-wrap data1 container">
    <h1>問題一覧</h1>
    <table class="tbl-r02">
        <tr>
            <th>科目</th>
            <th>問題</th>
            <th>答え</th>
        </tr>
        <% @questions.each do |obj| %>
        <tr>
            <td><%= obj.subject %></td>
            <td><%= obj.problem %></td>
            <td><%= obj.answer %></td>
            <td class="td"><a class="edit" href="/questions/edit/<%= obj.id %>"><i class="far fa-edit"></i>
                    <div class="edit-box">
                        <p class="text">編集</p>
                    </div>
                </a></td>
            <td class="td"><a class="delete" href="javascript:delData(<%= obj.id %>)"><i class="far fa-trash-alt"></i>
                    <div class="delete-box">
                        <p class="text">削除</p>
                    </div>
                </a></td>
        </tr>
        <% end %>
    </table>

    <div class="question-form">
        <h2>問題作成</h2>
        <%= form_for(@question,url:{controller: 'questions',action: 'create'}) do |f|%>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
            <label for="subject">教科</label>
            <%= f.select :subject, {'国語':1,'数学':2,'英語':3},{include_blank:'選択してください'},{class:'form-control'}  %>
        </div>
        <div class="form-group">
            <label for="problem">問題文</label>
            <%= f.text_area :problem ,{class: 'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :answer,'答え' %>
            <%= f.text_field :answer,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake1,'不正解１' %>
            <%= f.text_field :mistake1,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake2,'不正解2' %>
            <%= f.text_field :mistake2,{class:'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.label :mistake3,'不正解3' %>
            <%= f.text_field :mistake3,{class:'form-control'} %>
        </div>
        <div class="question-btn">
            <%= f.submit "保存する" ,{class: 'btn-sticky'} %>
        </div>
        <% end %>
    </div>
</div>

<script>
    function delData(num) {
        if (confirm('この問題を削除しますか？')) {
            document.location = "/questions/delete/" + num;
        }
        return false;
    }
</script>

app/views/questions/new.html.erb
<div class="question_wrap">
    <h1>テストガチャ</h1>
    <div class="description container">
        <p>ポイントを使ってテストガチャを回してみよう！<br>問題は<span class="subject">英語</span>の問題がランダムで作られるよ！<br>正解数に応じてポイントがもらえるよ(正解数とポイントの関係は下部に詳細あり)
            <br><span>高得点目指して頑張ろう！</span></p>
    </div>
    <table class="tbl-r02">
        <tr>
            <th>正解率</th>
            <th>ポイント</th>
        </tr>
        <tr>
            <th>100%</th>
            <td>200pt</td>
        </tr>
        <tr>
            <th>80%~99%</th>
            <td>150pt</td>
        </tr>
        <tr>
            <th>60%~80%未満</th>
            <td>70pt</td>
        </tr>
        <tr>
            <th>40%~60%未満</th>
            <td>50pt</td>
        </tr>
        <tr>
            <th>20%~40%未満</th>
            <td>20pt</td>
        </tr>
        <tr class="last">
            <th>20%未満</th>
            <td>10pt</td>
        </tr>
    </table>
    <div class="question_btn">
        <a class="btn-sticky" href="/questions/answer">ガチャを回す</a>
    </div>
    <div class="caution container">
        <p><span>注意:</span>ボタンを押すとすぐに始まります。制限時間は<span>10分</span>です<br><span>100ポイント消費<span></p>
    </div>
</div>