config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'
  get 'questions/new'
  get 'questions/edit/:id' =>'questions#edit'
  patch 'questions/edit/:id' => 'questions#update'
  get 'questions/answer'
  post 'questions/result' => 'questions#result'
  get 'questions/result' => 'posts#index'
  get 'questions/create' => 'questions#create'
  post 'questions/create' => 'questions#create'
  get 'questions/delete/:id' => 'questions#delete'
  post 'questions/answer_check' => 'questions#answer_check'
  get 'users/new'
  get 'users/create'
  get 'users/show/:id' => 'users#show'
  get 'users/edit/:id' =>'users#edit'
  patch 'users/edit/:id' => 'users#update'
  get 'users/delete/:id' => 'users#delete'
  post 'users/create' =>'users#create'
  post 'users/login' => 'users#login'
  get '' => 'home#index'
  get 'new' => 'home#new' 
  get 'posts' => 'posts#index'
  post 'posts' => 'posts#create'
  get 'posts/new'
  get 'posts/show'
  get 'posts/delete/:id' => 'posts#delete'
  get 'posts/edit/:id' => 'posts#edit'
  patch 'posts/edit/:id' => 'posts#edit'
  post 'login' => 'sessions#create'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :contacts,only: [:new,:create]
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/back' => 'contacts#back'
  get 'posts/questions/new' => 'post_questions#new'
  post 'posts/questions/new' =>'post_questions#create'
  get 'posts/questions/list' =>'post_questions#list'
  get 'posts/questions/start/:id' => 'post_questions#start'
  get 'posts/questions/answer/:id' => 'post_questions#answer'
  post 'posts/questions/answer/:id' => 'post_questions#result'
  get 'posts/questions/edit/:id' => 'post_questions#edit'
  patch 'posts/questions/edit/:id' => 'post_questions#update'
  get 'posts/questions/delete/:id' => 'post_questions#delete'
  get 'mylist/create/:id' => 'mylist#create'
  get 'mylist/destroy/:id' => 'mylist#destroy'
  get 'mylist/delete/:id' => 'mylist#delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/mylist.rb
class Mylist < ApplicationRecord
    belongs_to :user
    belongs_to :post_question
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    validates :content, presence: true,length: {maximum:100}
end

app/models/post_question.rb
class PostQuestion < ApplicationRecord
    belongs_to :user
    has_many :user_questions, dependent: :destroy
    has_many :mylists

    accepts_nested_attributes_for :user_questions, allow_destroy: true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :subject ,presence: true
    validates :problem ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password(validations: false)
    has_many :posts
    has_many :post_questions
    has_many :mylists
    mount_uploader :image, ImageUploader

    validates :name, presence: true, length: {maximum: 10}
    validates :mail, presence: true, uniqueness: true, on: :create
    validates :password_digest, presence: true,length: {minimum: 4},on: :create 
    validates :profile,length:{maximum:100}

    def mylist_by?(post_question_id)
        mylists.where(post_question_id: post_question_id).exists?
    end

#     with_options on: :step2 do
#         validate :validate_name_mail_check
#         validate :validate_name_password_check
#     end

# private
#     def validate_name_mail_check
#         errors.add(:mail, 'が間違っています') unless mail&.autheicate
#     end

#     def validate_name_password_check
#         errors.add(:password_digest,'が間違っています') unless password_digest&.present?
#     end
end

app/models/user_question.rb
class UserQuestion < ApplicationRecord
    belongs_to :post_question
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def  new
        @contact = Contact.new
    end

    def confirm
        @contact = Contact.new(contact_params)
        if @contact.invalid?
            render :new
        end
    end

    def back
        @contact = Contact.new(contact_params)
        render :new
    end


    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            ContactMailer.send_mail(@contact).deliver_now
            redirect_to '/contacts/new', notice: '送信しました'
        else
            render :new
        end
    end

    private

    def contact_params
        params.require(:contact).permit(:name,:email,:message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required
  before_action :current_user_redirect

  def index
  end

  def new
    @user =User.new
  end

  def login
    @user =User.new
  end
end

app/controllers/mylist_controller.rb
class MylistController < ApplicationController
    def create
        @post_question = PostQuestion.find(params[:id])
        current_user.mylists.create(post_question_id: @post_question.id)
    end

    def destroy
        @post_question = PostQuestion.find(params[:id])
        current_user.mylists.find_by(post_question_id: @post_question.id).destroy
    end

    def delete
        @mylist = Mylist.find(params[:id])
        @mylist.destroy
        redirect_to "/users/show/#{current_user.id}",notice: '削除しました'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @data = Post.all.order(created_at: :desc)
    @user = User.all
    @post = Post.new
  end

  def create
    @post = current_user.posts.new post_params

    if @post.save then
      flash[:notice] = "投稿が完了しました"
      redirect_to '/posts'
    else
      @data = Post.all
      render 'index'
    end
  end

  def show
  end

  def edit
    @post = Post.find(params[:id])
    if request.patch? then
      @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to '/users/show/' + current_user.id.to_s
    end
  end

  def delete
    @data = Post.find(params[:id])
    @data.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to "/users/show/" + current_user.id.to_s
  end

  
  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only:[:show,:edit]

  def create
    @user = User.new user_params
    if @user.save then
      session[:user_id]=@user.id
      now_time = Time.now
      @user.update(logged_in: now_time,point: 500)
      flash[:notice] = "登録しました"
      redirect_to controller: 'users', action: 'show', id:session[:user_id]
    else
      render template: "home/new"
    end
  end

  def show
    @mydata =current_user.posts
    @user = User.find(params[:id])
    @questions = current_user.post_questions
    @mylists = current_user.mylists
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id]) 
    if @user.update profile_params
      flash[:notice] = "更新しました"
      redirect_to "/users/show/" + @user.id.to_s
    else
      render "edit"
    end
  end

  def delete
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "退会しました"
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:mail, :name, :password, :image)
  end

  def profile_params
    params.require(:user).permit(:name, :image, :profile, :goal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mylist_helper.rb
module MylistHelper
end

app/helpers/post_questions_helper.rb
module PostQuestionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_questions_helper.rb
module UserQuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/confirm.html.erb
<div class="contact-confirm">
<h1>お問い合わせ確認</h1>
    <table class='tbl-r02'>
        <tr>
            <th class="text-center" style="width: 30%;">お名前</th>
            <td><%= @contact.name %></td>
        </tr>
        <tr>
            <th class="text-center">メッセージ</th>
            <td style="white-space: pre-wrap;"><%= @contact.message %></td>
        </tr>
    </table>
    <div class="confirm-form">
            <%= form_for @contact, url: contacts_back_path do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :message %>
            <div><%= f.submit '入力画面に戻る',{class:'btn-sticky'} %></div>
        <% end %>
    </div>
    <div class="confirm-form">
        <%= form_for(@contact) do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :message %>
            <div><%= f.submit '送信',{class:'btn-sticky'}%></div>
        <% end %>
    </div>
</div>

app/views/contacts/new.html.erb
<div class="contact-wrap container col-md-5">
    <h1>お問い合わせ</h1>
    <p>アプリの品質向上のため様々な意見をお願いします！</p>
    <div class="contact container">
        <%= form_for(@contact,url:{controller:'contacts',action:'confirm'}) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
            <label for="name">お名前</label>
            <%= f.text_field :name,{class:'form-control'}%>
        </div>

         <div class="form-group">
            <label for="message">お問い合わせ内容</label>
            <%= f.text_area  :message,{class:'form-control'} %>
        </div>

        <div class="edit-btn">
            <%= f.submit "入力内容確認" ,{class: 'btn-sticky'}%>
        </div>

        <% end %>
    </div>
</div>

app/views/mylist/_mylist.html.erb
<% if current_user.mylist_by?(post_question.id) %>
    <%= link_to "/mylist/destroy/#{post_question.id}" ,{remote: true, class:"mylist-btn"} do %>
        <div class="mylist-box">
            <i class="fas fa-minus icon"></i><p>マイリスト解除</p>
        </div>
    <% end %>
<% else %>
    <%= link_to "/mylist/create/#{post_question.id}", {remote: true,class:"mylist-btn"} do %>
        <div class="mylist-box">
            <i class="fas fa-plus icon"></i><p>マイリスト登録</p>
        </div>
    <% end %>
<% end %>

app/views/mylist/create.js.erb
<%# app/views/likes/create.js.erb %>

$('#mylist_buttons_<%= @post_question.id %>').html("<%= j(render "mylist/mylist", post_question: @post_question) %>");

app/views/mylist/destroy.js.erb
<%# app/views/likes/destroy.js.erb %>

$('#mylist_buttons_<%= @post_question.id %>').html("<%= j(render "mylist/mylist", post_question: @post_question) %>");

app/views/posts/edit.html.erb
<div class="posts-edit-wrap container col-md-5">
    <h1>投稿編集</h1>
    <div class="posts-edit">
        <%= form_for(@post, url:{controller:'posts', action:'edit', id:@post.id}) do |f| %>
        <div class="form-group">
            <%= f.label :content,'内容'%>
            <%= f.text_area :content ,{class:"form-control"} %>
        </div>
        <div class="edit-btn">
            <%= f.submit '更新',{class:'btn-sticky'} %>
        </div>
        <% end %>
    </div>
</div>

app/views/posts/index.html.erb
 <div class="data-wrap">
    <button class="btn post-btn" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="far fa-plus-square"></i>&nbsp;投稿
    </button>
    <%= form_for(@post, url:{controller:'posts', action:'create'}) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form collapse" id="collapseExample">
        <div class="input-group">
            <div class="cp_iptxt">
                <%= f.text_area :content ,class: "ef",placeholder:"投稿内容",id:'session_post'%>
                <span class="focus_bg"></span>
            </div>
            <span class="cp_iptxt-btn input-group-addon">
                <%= f.submit "投稿する" ,{class: "btn-sticky"}%>
            </span>
        </div>
        <% end %>
    </div>
    <div class="data container">
        <h1>タイムライン</h1>
        <ul class="post-lists container col-lg-8">
            <% @data.each do |obj| %>
            <li class="post-list">
                <div class="name-image">
                    <p class="name"><%= obj.user.name %></p>
                    <p class="image"><%=image_tag"#{obj.user.image.thumb2.url}",class:"card-img" %></p>
                </div>
                <div class="content">
                    <p><%= obj.content %></p>
                </div>
                <div class="time">
                    <p><%= l obj.created_at, format: :short %></p>
                </div>
            </li>
            <% end %>
        </ul>
    </div>
</div>

<script>
    function delData(num) {
        if (confirm('この投稿を削除しますか？')) {
            document.location = "/posts/delete/" + num;
        }
        return false;
    }
</script>

app/views/users/edit.html.erb
<div class="profile-edit-wrap">
    <h1>プロフィール編集</h1>
    <div class="profile-edit container col-lg-6">
        <%= form_for(@user,url:{controller:'users',action:'update'}) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :name, 'ニックネーム' %>
                <%= f.text_field :name,{class:'form-control'}%>
            </div>
            <div class="form-group">
                <%= f.label :profile, '自己紹介'%>
                <%= f.text_area  :profile,{class:'form-control'} %>
            </div>
            <div class="form-group">
                <%= f.label :goal, '目標'%>
                <%= f.text_area  :goal,{class:'form-control'} %>
            </div>
            <div class="form-group">
                <%= f.label :image, '画像を選択',{class:'image_input_btn'} %>
                <p class= 'image_name'>選択されていません</p>
                <%= f.file_field :image ,{class:'image_form'} %>
            </div>
            <div class="edit-btn">
                <%= f.submit "保存する" ,{class: 'btn-sticky'}%>
            </div>
        <% end %>
    </div>
</div>

<script>
    $('input').on('change', function () {
    var file = $(this).prop('files')[0];
    $('p').text(file.name);
});
</script>

app/views/users/show.html.erb
<div class="mypage-wrap container col-lg-6">
    <h1>プロフィール</h1>
    <div class="content">
        <div class="image">
            <p><%= @user.name %></p>
            <%= image_tag "#{@user.image}" %>
        </div>
        <div class=" introduce">
            <p>自己紹介</p>
            <div class="box">
                <%= @user.profile %>
            </div>
            <p>目標</p>
            <div class="box">
                <%= @user.goal %>
            </div>
            <div class="profifle-btn">
                <a class="btn-sticky" href="/users/edit/<%= @user.id%>">プロフィール編集</a>
            </div>
        </div>
    </div>

    <div class="mylist">
        <a class = "head" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><i class="fas fa-list icon"></i>マイリスト</a>
        <div class = "mylist-content card collapse" id ="collapseExample">
            <div>
            <table class="tbl-r02">
                <tr>
                    <th>問題名</th>
                    <th>問題説明</th>
                <tr>
                <% @mylists.each do |mylist|%>
                <tr>
                    <td class= "name"><%= mylist.post_question.name %></td>
                    <td class= "explanation"><%= mylist.post_question.explanation%></td>
                    <td class="solution"><%= link_to '問題を解く',"/posts/questions/start/#{mylist.post_question_id}",{class: "question-solution"}%></td>
                    <td class="td">
                        <a class="delete" href="javascript:delMylist(<%= mylist.id %>)">
                            <i class="far fa-trash-alt"></i>
                            <div class="delete-box">
                                <p class="text">削除</p>
                            </div>
                        </a>
                    </td>
                </tr>
                <% end %>
            </table>
            </div>
        </div>
    </div>

    <div class="content2">
        <div class="data1 card">
            <h2>投稿一覧</h2>
                <table class="tbl-r02">
                    <% @mydata.each do |obj| %>
                    <tr>
                        <td><%= obj.content %></td>
                        <td class="td"><a class="edit" href="/posts/edit/<%= obj.id %>"><i class="far fa-edit"></i>
                                <div class="edit-box">
                                    <p class="text">編集</p>
                                </div>
                            </a></td>
                        <td class="td"><a class="delete" href="javascript:delData(<%= obj.id %>)"><i
                                    class="far fa-trash-alt"></i>
                                <div class="delete-box">
                                    <p class="text">削除</p>
                                </div>
                            </a></td>
                    </tr>
                    <%end %>
                </table>
        </div>
        <div class="user_questions card">
            <h2>問題一覧</h2>
                <table class="tbl-r02">
                    <% @questions.each do |question| %>
                        <tr>
                            <td><%= question.name%></td>
                            <td class="td"><a class="edit" href="/posts/questions/edit/<%= question.id %>"><i class="far fa-edit"></i>
                                    <div class="edit-box">
                                        <p class="text">編集</p>
                                    </div>
                                </a></td>
                            <td class="td"><a class="delete" href="javascript:delquestion(<%= question.id %>)"><i
                                        class="far fa-trash-alt"></i>
                                    <div class="delete-box">
                                        <p class="text">削除</p>
                                    </div>
                                </a></td>
                        </tr>
                    <%end %>
                </table>
        </div>
    </div>
</div>
<script>
    function delData(num) {
        if (confirm('この投稿を削除しますか？')) {
            document.location = "/posts/delete/" + num;
        }
        return false;
    }
</script>

<script>
    function delquestion(num) {
        if (confirm('この問題を削除しますか？')) {
            document.location = "/posts/questions/delete/" + num;
        }
        return false;
    }
</script>

<script>
    function delMylist(num){
        if(confirm('削除しますか？')){
            document.location = "/mylist/delete/" + num;
        }
        return false;
    }
</script>